### ISSUE TITLE
Add the KidsPod app

### ISSUE THREAD

**Issue by kookster** [opawg/user-agents-v2#7]
re: https://podnews.net/press-release/kidspod-app

Here's the app's site https://kidspod.app/

This looks like a likely example US string I see in our logs:
`KidspodMobileClient/111 CFNetwork/1408.0.4 Darwin/22.5.0`

**Comment by kookster** [comment]
hmm, I did some testing, they are not setting the ua, I get generic requests from:
`AppleCoreMedia/1.0.0.20F75 (iPhone; U; CPU OS 16_5_1 like Mac OS X; en_us)`

I'll write them.

**Comment by johnspurlock** [comment]
Installed it, and it looks like it does send their custom UA only when the episode is downloaded, not played on demand - like many other iOS apps

Added to the AppleCoreMedia list: https://docs.google.com/spreadsheets/d/1YKQgt7xwLSdHmgtZew1TVD_RqzuA9W0ec0ab9BF9E0c/edit?usp=sharing

Since this is a new app, hopefully they can dedicate some resources to fixing it.

**Comment by kookster** [comment]
I heard back from their CEO, Jessica, and she passed this along to their dev team to work on (including the link to this issue).

**Comment by johnspurlock** [comment]
ok, thanks Andrew!
